"""
خودآزمایی‌های «Framstegstest» از کتاب Rivstart A1+A2 (Kopieringsunderlag).
Framstegstest 1 تا 6 — همه‌شون اینجان.
هر تست از چند بخش (section) تشکیل شده: نوع mcq (چندگزینه‌ای) یا fill (جای خالی).
برای fill: هر آیتم {"prompt": "...", "answer": "...", "accept": [گزینه‌های قابل قبول دیگه]}
بعضی بخش‌ها یه "passage" هم دارن (متن کامل برای نمایش، فقط جنبه‌ی مرجع داره).
"""

FRAMSTEGSTEST_1 = {
    "title": "Framstegstest 1",
    "subtitle": "فصل ۱ تا ۳",
    "sections": [
        {
            "num": 1, "title": "Vad svarar man?", "type": "mcq",
            "instructions": "جواب مناسب رو انتخاب کن.",
            "items": [
                {"prompt": "Jag söker jobb på restaurang.",
                 "options": ["Jaha. Lycka till!", "Det var så lite.", "Tack så mycket."], "correct": 0},
                {"prompt": "Vad har du för yrke?",
                 "options": ["På förskola.", "Jag är ingenjör.", "Jag har två barn."], "correct": 1},
                {"prompt": "Hur dags börjar filmen?",
                 "options": ["Hon är kvart över sju.", "Den är kvart över sju.", "Kvart över sju."], "correct": 2},
                {"prompt": "Är du gift?",
                 "options": ["Nej, men jag är sambo.", "Ja, jag är singel.", "Nej, vi bor inte ihop."], "correct": 0},
                {"prompt": "Hur är läget?",
                 "options": ["Ja, precis.", "Helt okej, tack.", "Jaha, vad kul!"], "correct": 1},
                {"prompt": "När är du född?", "options": ["1990.", "I Malmö.", "25 år."], "correct": 0},
                {"prompt": "Tack så mycket.", "options": ["Ja, tack.", "Helt okej.", "Det var så lite."], "correct": 2},
                {"prompt": "Anders och jag bor inte ihop.", "options": ["Jaha.", "Nähä.", "Ja."], "correct": 1},
                {"prompt": "Var ligger Kiruna?",
                 "options": ["Ja, jag bor där.", "I norra Sverige.", "Svenska och finska."], "correct": 1},
                {"prompt": "Ha det så bra!", "options": ["Du med!", "Bara bra, tack.", "Det är toppen!"], "correct": 0},
            ],
        },
        {
            "num": 2, "title": "Frågeord", "type": "fill",
            "instructions": "کلمه‌ی پرسشی درست رو تو جای خالی بنویس: Hur, När, Vad, Var, Varför, Varifrån, Vilken, Vilket (می‌تونی یه کلمه رو چندبار استفاده کنی).",
            "items": [
                {"prompt": "___ kommer din sambo? – Från Portugal.", "answer": "Varifrån"},
                {"prompt": "___ mår du? – Så där. Jag är lite trött.", "answer": "Hur"},
                {"prompt": "___ har du för telefonnummer? – 072-12 42 33.", "answer": "Vad"},
                {"prompt": "___ gammal är morfar? – 89 år.", "answer": "Hur"},
                {"prompt": "___ tid har vi fikapaus? – Klockan två, tror jag.", "answer": "Vilken"},
                {"prompt": "___ studerar du italienska? – Min pojkvän kommer från Italien.", "answer": "Varför"},
                {"prompt": "___ mycket kaffe dricker du? – Inte så mycket. Bara två koppar per dag.", "answer": "Hur"},
                {"prompt": '___ heter "cat" på svenska? – "Katt".', "answer": "Vad"},
                {"prompt": "___ dags går bussen? – Fem över nio.", "answer": "Hur"},
                {"prompt": "___ gata bor du på? – Prästgatan.", "answer": "Vilken"},
                {"prompt": "___ nummer? – 12.", "answer": "Vilket"},
                {"prompt": "___ slutar vi? – Klockan fem.", "answer": "När"},
                {"prompt": "___ många barn har du? – Tre.", "answer": "Hur"},
                {"prompt": "___ bor du? – I Uppsala.", "answer": "Var"},
                {"prompt": "___ är klockan? – Tio i åtta.", "answer": "Vad"},
            ],
        },
        {
            "num": 3, "title": "Verb", "type": "fill",
            "instructions": "فعل مناسب از این‌ها رو تو جای خالیِ درست بنویس: längtar, bor, vaknar, tar, äter, pluggar, stiger, surfar, tränar, lyssnar, dricker, fikar, träffar, kommer, trivs",
            "passage": (
                "Milena ___(1)___ från Brasilien, men nu ___(2)___ hon i Stockholm och ___(3)___ "
                "filosofi på universitetet. Varje morgon ___(4)___ Milena klockan halv sju och hon "
                "___(5)___ upp direkt. Hon ___(6)___ en kopp te och ___(7)___ en banan och sedan går "
                "hon till gymmet och ___(8)___. Klockan tio ___(9)___ hon bussen till universitetet. "
                "Efter universitetet ___(10)___ hon en kompis och de ___(11)___ på ett kafé i stan. "
                "På kvällen ___(12)___ hon på internet och ___(13)___ på musik. Milena ___(14)___ bra "
                "i Sverige, men ibland ___(15)___ hon efter solen i Brasilien."
            ),
            "items": [
                {"prompt": "(1)", "answer": "kommer"}, {"prompt": "(2)", "answer": "bor"},
                {"prompt": "(3)", "answer": "pluggar"}, {"prompt": "(4)", "answer": "vaknar"},
                {"prompt": "(5)", "answer": "stiger"}, {"prompt": "(6)", "answer": "dricker"},
                {"prompt": "(7)", "answer": "äter"}, {"prompt": "(8)", "answer": "tränar"},
                {"prompt": "(9)", "answer": "tar"}, {"prompt": "(10)", "answer": "träffar"},
                {"prompt": "(11)", "answer": "fikar"}, {"prompt": "(12)", "answer": "surfar"},
                {"prompt": "(13)", "answer": "lyssnar"}, {"prompt": "(14)", "answer": "trivs"},
                {"prompt": "(15)", "answer": "längtar"},
            ],
        },
        {
            "num": 4, "title": "Substantiv: obestämd och bestämd form", "type": "fill",
            "instructions": "شکل نکره یا معرفه‌ای که کمه رو بنویس (مثال: en mössa → mössan).",
            "items": [
                {"prompt": "___ (نکره) → familjen (معرفه)", "answer": "en familj"},
                {"prompt": "ett pass (نکره) → ___ (معرفه)", "answer": "passet"},
                {"prompt": "___ (نکره) → lägenheten (معرفه)", "answer": "en lägenhet"},
                {"prompt": "en timme (نکره) → ___ (معرفه)", "answer": "timmen"},
                {"prompt": "___ (نکره) → livet (معرفه)", "answer": "ett liv"},
                {"prompt": "en sambo (نکره) → ___ (معرفه)", "answer": "sambon"},
                {"prompt": "___ (نکره) → pausen (معرفه)", "answer": "en paus"},
                {"prompt": "ett piano (نکره) → ___ (معرفه)", "answer": "pianot"},
                {"prompt": "___ (نکره) → programmet (معرفه)", "answer": "ett program"},
                {"prompt": "en gata (نکره) → ___ (معرفه)", "answer": "gatan"},
            ],
        },
        {
            "num": 5, "title": "Ordföljd: Påståenden och ja/nej-frågor", "type": "fill",
            "instructions": "از جمله‌ی خبری یه سؤال بله/خیر بساز، یا برعکس (مثال: Noi kommer från Thailand. ↔ Kommer Noi från Thailand?).",
            "items": [
                {"prompt": "Vi har fikapaus klockan tio. → سؤال بساز:", "answer": "Har vi fikapaus klockan tio?"},
                {"prompt": "Trivs Alberto i Sverige? → جمله‌ی خبری بساز:", "answer": "Alberto trivs i Sverige."},
                {"prompt": "Renate bor i Sverige nu. → سؤال بساز:", "answer": "Bor Renate i Sverige nu?"},
                {"prompt": "Jobbar Charlie på ett IT-företag? → جمله‌ی خبری بساز:",
                 "answer": "Charlie jobbar på ett IT-företag."},
                {"prompt": "Anna studerar ekonomi i Lund. → سؤال بساز:", "answer": "Studerar Anna ekonomi i Lund?"},
            ],
        },
        {
            "num": 6, "title": "Klockan", "type": "fill",
            "instructions": "ساعت رو به سوئدی بنویس (مثال: 9:00 → Klockan är nio.) — نوشتن یا ننوشتن «Klockan är» اشکالی نداره.",
            "items": [
                {"prompt": "8:10", "answer": "tio över åtta"},
                {"prompt": "9:55", "answer": "fem i tio"},
                {"prompt": "3:30", "answer": "halv fyra"},
                {"prompt": "6:15", "answer": "kvart över sex"},
                {"prompt": "10:45", "answer": "kvart i elva"},
                {"prompt": "11:05", "answer": "fem över elva"},
                {"prompt": "4:50", "answer": "tio i fem"},
                {"prompt": "2:40", "answer": "tjugo i tre"},
                {"prompt": "1:25", "answer": "fem i halv två"},
                {"prompt": "7:35", "answer": "fem över halv åtta"},
            ],
        },
        {
            "num": 7, "title": "Verb: imperativ och presens", "type": "fill",
            "instructions": "شکل امر یا زمان حال که کمه رو بنویس (مثال: Ring! ↔ ringer).",
            "items": [
                {"prompt": "läs! (امر) → ___ (حال)", "answer": "läser"},
                {"prompt": "___ (امر) → ligger (حال)", "answer": "ligg!"},
                {"prompt": "sluta! (امر) → ___ (حال)", "answer": "slutar"},
                {"prompt": "___ (امر) → är (حال)", "answer": "var!"},
                {"prompt": "ät! (امر) → ___ (حال)", "answer": "äter"},
                {"prompt": "___ (امر) → kommer (حال)", "answer": "kom!"},
                {"prompt": "skriv! (امر) → ___ (حال)", "answer": "skriver"},
                {"prompt": "___ (امر) → har (حال)", "answer": "ha!"},
                {"prompt": "gå! (امر) → ___ (حال)", "answer": "går"},
                {"prompt": "___ (امر) → spelar (حال)", "answer": "spela!"},
            ],
        },
        {
            "num": 8, "title": "Ordföljd", "type": "fill",
            "instructions": "کلمات پخش‌شده رو مرتب کن و جمله‌ی کامل بساز. اگه ترتیب تو فرق داشت ولی گرامرش درست بود، خودت بهش نمره بده.",
            "items": [
                {"prompt": "Efter ___ . (diskar / Renate / middagen)", "answer": "Efter middagen diskar Renate."},
                {"prompt": "På ___ . (te / dricker / Erik / morgonen / kopp / en)",
                 "answer": "På morgonen dricker Erik en kopp te."},
                {"prompt": "Varför ___? (Sverige / du / i / bor)", "answer": "Varför bor du i Sverige?"},
                {"prompt": "I ___ . (Albertos / sommar / kommer / mamma / Sverige / till)",
                 "answer": "I sommar kommer Albertos mamma till Sverige."},
                {"prompt": "Klockan ___ . (Alice / sig / går / tolv / lägger / och)",
                 "answer": "Klockan tolv går Alice och lägger sig."},
                {"prompt": "Anita ___ . (engelska / inte / talar)", "answer": "Anita talar inte engelska."},
                {"prompt": "Hur ___? (kursen / personer / ni / är / många / på)",
                 "answer": "Hur många personer är ni på kursen?"},
                {"prompt": "Vilken ___? (lunch / ni / äter / tid)", "answer": "Vilken tid äter ni lunch?"},
                {"prompt": "Ann-Sofie ___ . (Sverige / inte / bor / i)", "answer": "Ann-Sofie bor inte i Sverige."},
                {"prompt": "Klockan ___ . (biff och pommes frites / tolv / restaurang / i / Anna / äter / på / en / stan)",
                 "answer": "Klockan tolv äter Anna biff och pommes frites på en restaurang i stan."},
            ],
        },
        {
            "num": 9, "title": "Prepositioner", "type": "fill",
            "instructions": "حرف اضافه‌ی درست رو بنویس.",
            "passage": (
                "Carlos kommer ___(1)___ Argentina. Han är gift ___(2)___ Fredrika. Carlos är ekonom "
                "och Fredrika är journalist. Carlos jobbar ___(3)___ en bank ___(4)___ stan. Fredrika "
                "är väldigt intresserad ___(5)___ musik och just nu skriver hon en artikel ___(6)___ "
                "svensk jazz.\n\nEmilia arbetar ___(7)___ en restaurang i Uppsala. Hon jobbar ___(8)___ "
                "sex och halv två. Hon kommer hem klockan två ___(9)___ natten. Då chattar hon "
                "___(10)___ en kompis i USA. Hon berättar ___(11)___ restaurangen och jobbet där. Vid "
                "tre går hon och lägger sig och sover ___(12)___ klockan elva. Hon äter yoghurt och "
                "müsli ___(13)___ frukost. Klockan fem tar hon bussen ___(14)___ jobbet. På bussen "
                "lyssnar hon ___(15)___ musik och skriver mejl."
            ),
            "items": [
                {"prompt": "(1)", "answer": "från"}, {"prompt": "(2)", "answer": "med"},
                {"prompt": "(3)", "answer": "på"}, {"prompt": "(4)", "answer": "i"},
                {"prompt": "(5)", "answer": "av"}, {"prompt": "(6)", "answer": "om"},
                {"prompt": "(7)", "answer": "på"}, {"prompt": "(8)", "answer": "mellan"},
                {"prompt": "(9)", "answer": "på"}, {"prompt": "(10)", "answer": "med"},
                {"prompt": "(11)", "answer": "om"}, {"prompt": "(12)", "answer": "till"},
                {"prompt": "(13)", "answer": "till"}, {"prompt": "(14)", "answer": "till"},
                {"prompt": "(15)", "answer": "på"},
            ],
        },
    ],
}

FRAMSTEGSTEST_2 = {
    "title": "Framstegstest 2",
    "subtitle": "فصل ۴ تا ۶",
    "sections": [
        {
            "num": 1, "title": "Vad svarar man?", "type": "mcq",
            "instructions": "جواب مناسب رو انتخاب کن.",
            "items": [
                {"prompt": "Något annat?",
                 "options": ["Ja, tack. Det var bra så.", "Nej, tack. Det var bra så.", "Tack så mycket."], "correct": 1},
                {"prompt": "Vill du ha kvittot?",
                 "options": ["Ja, tack.", "Det var bra så.", "Tack, tack."], "correct": 0},
                {"prompt": "Vill du hänga med på bio ikväll?",
                 "options": ["Jaha!", "Jaså.", "Ja, gärna."], "correct": 2},
                {"prompt": "Jag kan inte gå på festen på lördag.",
                 "options": ["Vad synd!", "Tja, varför inte?", "Vad kul!"], "correct": 0},
                {"prompt": "Vad brukar du göra på fredagar?",
                 "options": ["Jag brukar äta middag med vänner.", "Jag brukar åt middag med vänner.",
                             "Jag brukar äter middag med vänner."], "correct": 0},
                {"prompt": "Jag ska gå på Nobelfesten!",
                 "options": ["Ja, absolut!", "Nej, men okej.", "Är det sant?!"], "correct": 2},
                {"prompt": "Vad kostar den där bullen?",
                 "options": ["Den här?", "Ja, tack.", "Javisst."], "correct": 0},
                {"prompt": "Ikväll ska vi äta pizza.",
                 "options": ["Det var bra så.", "Ja, tack.", "Vad gott!"], "correct": 2},
                {"prompt": "Vad ska du göra på lördag?",
                 "options": ["Tja, varför inte?", "Jag vet inte. Hur så?", "Nja, jag vet inte."], "correct": 1},
                {"prompt": "Har du många syskon?",
                 "options": ["Ja, sju kusiner.", "Nej, bara en moster.", "Nej, bara en syster."], "correct": 2},
            ],
        },
        {
            "num": 2, "title": "Substantiv: singular och plural", "type": "fill",
            "instructions": "شکل مفرد یا جمعی که کمه رو بنویس.",
            "items": [
                {"prompt": "ett jobb (مفرد) → ___ (جمع نکره)", "answer": "jobb"},
                {"prompt": "___ (مفرد نکره) → personer (جمع)", "answer": "en person"},
                {"prompt": "ett yrke (مفرد) → ___ (جمع نکره)", "answer": "yrken"},
                {"prompt": "___ (مفرد نکره) → flaskor (جمع)", "answer": "en flaska"},
                {"prompt": "en kompis (مفرد) → ___ (جمع نکره)", "answer": "kompisar"},
                {"prompt": "___ (مفرد نکره) → företag (جمع)", "answer": "ett företag"},
                {"prompt": "en förskola (مفرد) → ___ (جمع نکره)", "answer": "förskolor"},
                {"prompt": "___ (مفرد نکره) → böcker (جمع)", "answer": "en bok"},
                {"prompt": "en läkare (مفرد) → ___ (جمع نکره)", "answer": "läkare"},
                {"prompt": "___ (مفرد نکره) → tidningar (جمع)", "answer": "en tidning"},
            ],
        },
        {
            "num": 3, "title": "Veckodagar och årstider", "type": "fill",
            "instructions": "A: روزهای هفته رو کامل کن (måndag داده شده). B: اسم فصل رو بنویس.",
            "items": [
                {"prompt": "A2: ___ (بعد از måndag)", "answer": "tisdag"},
                {"prompt": "A3: ___", "answer": "onsdag"},
                {"prompt": "A4: ___", "answer": "torsdag"},
                {"prompt": "A5: ___", "answer": "fredag"},
                {"prompt": "A6: ___", "answer": "lördag"},
                {"prompt": "A7: ___", "answer": "söndag"},
                {"prompt": "B1: december–februari → ___", "answer": "vinter"},
                {"prompt": "B2: mars–maj → ___", "answer": "vår"},
                {"prompt": "B3: juni–augusti → ___", "answer": "sommar"},
                {"prompt": "B4: september–november → ___", "answer": "höst"},
            ],
        },
        {
            "num": 4, "title": "Verb grupp 1–3: imperativ, infinitiv, presens och preteritum", "type": "fill",
            "instructions": "A: جدول فعل‌ها رو کامل کن. B: فعل مناسب رو از این‌ها انتخاب و با شکل درست بنویس: sov, tyck, ta, väck, skriv, gå, fika, kom (همه به شکل امر نوشته شدن).",
            "items": [
                {"prompt": "A — må!: اینفینیتیو", "answer": "må"},
                {"prompt": "A — må!: حال", "answer": "mår"},
                {"prompt": "A — må!: گذشته", "answer": "mådde"},
                {"prompt": "A — läs!: اینفینیتیو", "answer": "läsa"},
                {"prompt": "A — läs!: حال", "answer": "läser"},
                {"prompt": "A — läs!: گذشته", "answer": "läste"},
                {"prompt": "A — ring!: اینفینیتیو", "answer": "ringa"},
                {"prompt": "A — ring!: حال", "answer": "ringer"},
                {"prompt": "A — ring!: گذشته", "answer": "ringde"},
                {"prompt": "A — prata!: اینفینیتیو", "answer": "prata"},
                {"prompt": "A — prata!: حال", "answer": "pratar"},
                {"prompt": "A — prata!: گذشته", "answer": "pratade"},
                {"prompt": "B1: – Vad gjorde du igår? – Jag ___ en promenad med Enrique i parken.", "answer": "tog"},
                {"prompt": "B1: Sedan ___ vi på ett kafé i stan.", "answer": "fikade"},
                {"prompt": "B2: Jag måste ___ ett mejl till min moster i Skottland.", "answer": "skriva"},
                {"prompt": "B2: Hon ___ till Göteborg på tisdag.", "answer": "kommer"},
                {"prompt": "B3: God natt, mamma. ___ mig klockan åtta imorgon!", "answer": "Väck"},
                {"prompt": "B3: Okej. ___ gott!", "answer": "Sov"},
                {"prompt": "B4: Ska vi ___ på bio och se Dracula ikväll?", "answer": "gå"},
                {"prompt": "B4: Nja... Jag ___ inte så mycket om vampyrfilmer.", "answer": "tycker"},
            ],
        },
        {
            "num": 5, "title": "Ordföljd", "type": "fill",
            "instructions": "کلمات پخش‌شده رو مرتب کن.",
            "items": [
                {"prompt": "På ___ . (Berit / på / alltid / vattengympa / lördagar / går)",
                 "answer": "På lördagar går Berit alltid på vattengympa."},
                {"prompt": "Emma ___ . (skräckfilmer / inte / se / vill)", "answer": "Emma vill inte se skräckfilmer."},
                {"prompt": "I ___ . (mådde / så bra / fredags / inte / jag)",
                 "answer": "I fredags mådde jag inte så bra."},
                {"prompt": "Ibland ___ . (landet / på / åker / Patrik och Elsa / auktioner / på)",
                 "answer": "Ibland åker Patrik och Elsa på auktioner på landet."},
                {"prompt": "Ralf ___ . (gå / brukar / kyrkan / sällan / i)",
                 "answer": "Ralf brukar sällan gå i kyrkan."},
            ],
        },
        {
            "num": 6, "title": "Hjälpverb", "type": "fill",
            "instructions": "فعل کمکی مناسب رو از این‌ها بنویس: brukar, skulle vilja, måste, kan, vill, ska.",
            "passage": (
                "1  – ___(1)___ du gå på teater med mig på fredag?\n"
                "   – Tyvärr, jag ___(2)___ inte. Jag ___(3)___ hjälpa min syster. Hon ___(4)___ flytta till en ny lägenhet.\n\n"
                "2  – ___(5)___ jag få en stor kaffe latte, tack.\n"
                "   – Ja, tack. Något annat?\n"
                "   – Ja, jag ___(6)___ ha en mazarin också, tack.\n\n"
                "3  – Vad ___(7)___ du göra på jularna?\n"
                "   – Jag ___(8)___ träffa min familj.\n\n"
                "4  – ___(9)___ du dansa tango?\n"
                "   – Nej, men jag ___(10)___ börja på en tangokurs nästa vecka."
            ),
            "items": [
                {"prompt": "(1)", "answer": "Vill"}, {"prompt": "(2)", "answer": "kan"},
                {"prompt": "(3)", "answer": "måste", "accept": ["ska"]}, {"prompt": "(4)", "answer": "ska"},
                {"prompt": "(5)", "answer": "Kan"}, {"prompt": "(6)", "answer": "skulle vilja", "accept": ["vill"]},
                {"prompt": "(7)", "answer": "brukar"}, {"prompt": "(8)", "answer": "brukar"},
                {"prompt": "(9)", "answer": "Kan"}, {"prompt": "(10)", "answer": "ska"},
            ],
        },
        {
            "num": 7, "title": "Adjektiv", "type": "fill",
            "instructions": "شکل درست صفت رو بنویس.",
            "passage": (
                "Adam tycker mycket om att gå på bio. Han älskar ___(1)___ (romantisk) filmer, men igår "
                "såg han en ___(2)___ (läskig) skräckfilm. Den var ___(3)___ (japansk). Adam lyssnar "
                "mycket på radio också. Förra veckan hörde han ett ___(4)___ (rolig) program om ett "
                "___(5)___ (gammal) hus i Lappland som man ska göra om till casino."
            ),
            "items": [
                {"prompt": "(1)", "answer": "romantiska"}, {"prompt": "(2)", "answer": "läskig"},
                {"prompt": "(3)", "answer": "japansk"}, {"prompt": "(4)", "answer": "roligt"},
                {"prompt": "(5)", "answer": "gammalt"},
            ],
        },
        {
            "num": 8, "title": "Objektspronomen", "type": "fill",
            "instructions": "ضمیر مفعولی درست رو بنویس.",
            "items": [
                {"prompt": "Kan du mejla ___ (han)? – Absolut. Jag gör det nu direkt.", "answer": "honom"},
                {"prompt": "Kommer ni till ___ (vi) på lördag? – Gärna!", "answer": "oss"},
                {"prompt": "Vi kommer gärna till ___ (ni). – Vad trevligt. Välkomna!", "answer": "er"},
                {"prompt": "Älskar du ___ (jag)? – Ja, det är klart!", "answer": "mig"},
                {"prompt": "Sara är sjuk. Jag måste ringa ___ (hon). – Hälsa Sara från mig!", "answer": "henne"},
                {"prompt": "Ska jag hjälpa ___ (du) med läxan, Fia? – Nej pappa, jag kan själv.", "answer": "dig"},
                {"prompt": "Där är Martin och Bella. Jag måste prata med ___ (de). – Okej. Vi ses sedan.", "answer": "dem"},
            ],
        },
        {
            "num": 9, "title": "Verb i grupp 4: preteritum", "type": "fill",
            "instructions": "فعل رو به preteritum (گذشته) بنویس.",
            "items": [
                {"prompt": "gör", "answer": "gjorde"}, {"prompt": "äter", "answer": "åt"},
                {"prompt": "kommer", "answer": "kom"}, {"prompt": "tar", "answer": "tog"},
                {"prompt": "ligger", "answer": "låg"}, {"prompt": "sover", "answer": "sov"},
                {"prompt": "vet", "answer": "visste"}, {"prompt": "säger", "answer": "sa", "accept": ["sade"]},
                {"prompt": "finns", "answer": "fanns"}, {"prompt": "går", "answer": "gick"},
                {"prompt": "är", "answer": "var"}, {"prompt": "vill", "answer": "ville"},
                {"prompt": "får", "answer": "fick"},
            ],
        },
        {
            "num": 10, "title": "Possessiva pronomen", "type": "fill",
            "instructions": "ضمیر ملکی درست رو بنویس.",
            "items": [
                {"prompt": "När köpte du ___? (du / en dator)", "answer": "din dator"},
                {"prompt": "___ är jättesöta! (de / katter)", "answer": "Deras katter"},
                {"prompt": "Jag tycker mycket om ___. (ni / ett hus)", "answer": "ert hus"},
                {"prompt": "Jag ska hälsa på ___. (jag / kusiner)", "answer": "mina kusiner"},
                {"prompt": "Jag har inte ___. (du / ett telefonnummer)", "answer": "ditt telefonnummer"},
                {"prompt": "___ bor i Kanada. (hon / systrar)", "answer": "Hennes systrar"},
                {"prompt": "Vad heter ___? (ni / söner)", "answer": "era söner"},
                {"prompt": "Gustav är sjuk så jag ska gå ut med ___ idag. (han / en hund)", "answer": "hans hund"},
                {"prompt": "___ är så goda! (du / kanelbullar)", "answer": "Dina kanelbullar"},
                {"prompt": "___ är gult. (vi / ett piano)", "answer": "Vårt piano"},
            ],
        },
    ],
}

FRAMSTEGSTEST_3 = {
    "title": "Framstegstest 3",
    "subtitle": "فصل ۷ تا ۹",
    "sections": [
        {
            "num": 1, "title": "Vad svarar man?", "type": "mcq",
            "instructions": "جواب مناسب رو انتخاب کن.",
            "items": [
                {"prompt": "När är Sveriges nationaldag? (= 6/6)",
                 "options": ["Sjätte juni.", "Sjunde juni.", "Sextionde juni."], "correct": 0},
                {"prompt": "Det finns tyvärr inte så mycket att se i min stad.",
                 "options": ["Jaha.", "Det låter härligt!", "Nähä."], "correct": 2},
                {"prompt": "Har ni öppet köp?",
                 "options": ["Ja, i 30 dagar.", "Ja, för 30 dagar.", "Ja, för 30 dagar sedan."], "correct": 0},
                {"prompt": "Vill du ha hjälp?",
                 "options": ["Då ska vi se.", "Nej, tack. Jag tittar bara.", "Tack, det var bra så."], "correct": 1},
                {"prompt": "Sitter skorna bra?",
                 "options": ["Nej, tack.", "Ja, det har jag.", "Ja, de är perfekta."], "correct": 2},
                {"prompt": "Hur mycket tar ni för den här slipsen?",
                 "options": ["575 kronor.", "Vi har många fina slipsar.", "Tack, jag tar den."], "correct": 0},
                {"prompt": "När har vi fikapaus?",
                 "options": ["För en halvtimme sedan.", "I en halvtimme.", "Om en halvtimme."], "correct": 2},
                {"prompt": "Vad är det för datum idag?",
                 "options": ["April fjorton.", "Fjortonde april.", "Fjorton april."], "correct": 1},
                {"prompt": "Går bussen ofta?",
                 "options": ["Ja, var tionde minut.", "Ja, varje tio minuter.", "Ja, var tio minuter."], "correct": 0},
                {"prompt": "Det tar ungefär en timme att gå till stationen.",
                 "options": ["Oj, jag måste inte gå så långt.", "Oj, jag orkar inte gå så långt.",
                             "Oj, jag behöver inte gå så långt."], "correct": 1},
            ],
        },
        {
            "num": 2, "title": "Adjektiv: motsatser", "type": "fill",
            "instructions": "متضاد صفت رو بنویس (مثال: billig → dyr).",
            "items": [
                {"prompt": "ljus", "answer": "mörk"}, {"prompt": "bra", "answer": "dålig"},
                {"prompt": "ny", "answer": "gammal"}, {"prompt": "bred", "answer": "smal"},
                {"prompt": "lång", "answer": "kort"}, {"prompt": "rolig", "answer": "tråkig"},
                {"prompt": "god", "answer": "äcklig"}, {"prompt": "mjuk", "answer": "hård"},
                {"prompt": "stor", "answer": "liten"}, {"prompt": "snygg/fin/vacker", "answer": "ful"},
            ],
        },
        {
            "num": 3, "title": "Indefinita pronomen", "type": "fill",
            "instructions": "ingen, inget, inga یا någon, något, några — کدوم مناسبه؟",
            "items": [
                {"prompt": "Felix har ___ arbete just nu. – Oj då. Stackars Felix!", "answer": "inget"},
                {"prompt": "Och han har inte ___ pengar heller.", "answer": "några"},
                {"prompt": "Jag måste gå till mataffären. Vi har ___ mjölk hemma.", "answer": "ingen"},
                {"prompt": "Kan du köpa ___ bröd också?", "answer": "något"},
                {"prompt": "Har du ___ röd klänning?", "answer": "någon", "accept": ["ingen"]},
                {"prompt": "Nej, jag har faktiskt ___ klänningar.", "answer": "inga"},
            ],
        },
        {
            "num": 4, "title": "Substantivets former", "type": "fill",
            "instructions": "شکلی که کمه رو از جدول بنویس (en kamera / kameran / kameror / kamerorna و غیره).",
            "items": [
                {"prompt": "kamera — Singular obestämd (plural bestämd: kamerorna)", "answer": "en kamera"},
                {"prompt": "kamera — Singular bestämd", "answer": "kameran"},
                {"prompt": "kamera — Plural obestämd", "answer": "kameror"},
                {"prompt": "säng — Singular obestämd (sing. bestämd: sängen)", "answer": "en säng"},
                {"prompt": "säng — Plural obestämd", "answer": "sängar"},
                {"prompt": "säng — Plural bestämd", "answer": "sängarna"},
                {"prompt": "mobil — Singular obestämd (plural obestämd: mobiler)", "answer": "en mobil"},
                {"prompt": "mobil — Singular bestämd", "answer": "mobilen"},
                {"prompt": "mobil — Plural bestämd", "answer": "mobilerna"},
                {"prompt": "täcke — Singular bestämd (sing. obestämd: ett täcke)", "answer": "täcket"},
                {"prompt": "täcke — Plural obestämd", "answer": "täcken"},
                {"prompt": "täcke — Plural bestämd", "answer": "täckena"},
                {"prompt": "barn — Singular bestämd (sing. obestämd: ett barn)", "answer": "barnet"},
                {"prompt": "barn — Plural obestämd", "answer": "barn"},
                {"prompt": "barn — Plural bestämd", "answer": "barnen"},
                {"prompt": "tandläkare — Singular obestämd (sing. bestämd: tandläkaren)", "answer": "en tandläkare"},
                {"prompt": "tandläkare — Plural obestämd", "answer": "tandläkare"},
                {"prompt": "tandläkare — Plural bestämd", "answer": "tandläkarna"},
            ],
        },
        {
            "num": 5, "title": "Adjektiv: komparation", "type": "fill",
            "instructions": "شکل درست صفت رو بنویس.",
            "items": [
                {"prompt": "Mjölk är ___ (billig) än vin.", "answer": "billigare"},
                {"prompt": "Vad är ___ (god), kanelbullar eller mazariner?", "answer": "godast"},
                {"prompt": "Stella är ___ (lång) än Kim.", "answer": "längre"},
                {"prompt": "Mexico City är ___ (stor) än Stockholm.", "answer": "större"},
                {"prompt": "Jag tycker att den här filmen är ___ (bra) än den vi såg igår.", "answer": "bättre"},
                {"prompt": "Svenskar dricker ___ (mycket) kaffe än tyskar.", "answer": "mer"},
                {"prompt": "Vilket universitet är ___ (gammal), Lunds eller Stockholms?", "answer": "äldst"},
                {"prompt": "Min katt är ___ (liten) än din.", "answer": "mindre"},
            ],
        },
        {
            "num": 6, "title": "Ordföljd", "type": "fill",
            "instructions": "کلمات پخش‌شده رو مرتب کن.",
            "items": [
                {"prompt": "På lördag ___ . (checka / vi / in / klockan sju / måste)",
                 "answer": "På lördag måste vi checka in klockan sju."},
                {"prompt": "På fredagar ___ . (klockan fyra / hem / brukar / alltid / jag / gå)",
                 "answer": "På fredagar brukar jag alltid gå hem klockan fyra."},
                {"prompt": "Bananer ___ . (om / jag / tycker / inte)", "answer": "Bananer tycker jag inte om."},
                {"prompt": "Nästa vecka ___ . (vi / min mormor / på / hälsa / ska)",
                 "answer": "Nästa vecka ska vi hälsa på min mormor."},
                {"prompt": "Om ett par minuter ___ . (vid / bussen / gå / vi / av / ska / Nytorget)",
                 "answer": "Om ett par minuter ska vi gå av bussen vid Nytorget."},
            ],
        },
        {
            "num": 7, "title": "Verb: supinum", "type": "fill",
            "instructions": "فعل رو به supinum بنویس.",
            "items": [
                {"prompt": "fika (1)", "answer": "fikat"}, {"prompt": "ringa (2a)", "answer": "ringt"},
                {"prompt": "köpa (2b)", "answer": "köpt"}, {"prompt": "må (3)", "answer": "mått"},
                {"prompt": "ta (4a)", "answer": "tagit"}, {"prompt": "göra (4b)", "answer": "gjort"},
            ],
        },
        {
            "num": 8, "title": "Väder", "type": "fill",
            "instructions": "تصویر هوا رو توصیف کن.",
            "items": [
                {"prompt": "☀️ تصویر ۱ (آفتاب و ابر)", "answer": "Solen skiner", "accept": ["det är soligt"]},
                {"prompt": "☁️ تصویر ۲ (ابری)", "answer": "Det är mulet", "accept": ["det är molnigt"]},
                {"prompt": "❄️ تصویر ۳ (برف)", "answer": "Det snöar"},
                {"prompt": "💨 تصویر ۴ (باد)", "answer": "Det blåser"},
                {"prompt": "🌧️ تصویر ۵ (باران)", "answer": "Det regnar"},
            ],
        },
        {
            "num": 9, "title": "Hjälpverb", "type": "fill",
            "instructions": "فعل کمکی مناسب رو از این‌ها بنویس: måste, får, borde, hinner, orkar, behöver.",
            "items": [
                {"prompt": "Man ___ inte parkera här. Det är förbjudet.", "answer": "får"},
                {"prompt": "Du ___ inte diska idag. Jag kan göra det.", "answer": "behöver"},
                {"prompt": "Filmen börjar om 10 minuter, så vi ___ inte fika nu.", "answer": "hinner"},
                {"prompt": "Pappa, jag ___ inte städa mitt rum idag. Jag är så trött!", "answer": "orkar"},
                {"prompt": "Nej, du ___ göra det nu!", "answer": "måste"},
                {"prompt": "Du ___ inte röka så mycket.", "answer": "borde"},
            ],
        },
        {
            "num": 10, "title": "Adverb: hem/hemma", "type": "fill",
            "instructions": "hem یا hemma — کدوم مناسبه؟",
            "items": [
                {"prompt": "På lördag ska Marko åka ___ till Serbien.", "answer": "hem"},
                {"prompt": "På semestern bodde Anja ___ hos en kompis.", "answer": "hemma"},
                {"prompt": "Camilla tycker om att vara ___ i Göteborg på somrarna.", "answer": "hemma"},
                {"prompt": "Nu ska jag gå ___ till Pelle.", "answer": "hem"},
                {"prompt": "Ikväll ska jag vara ___ och titta på teve.", "answer": "hemma"},
            ],
        },
        {
            "num": 11, "title": "Gå eller åk?", "type": "fill",
            "instructions": "شکل درست gå یا åk رو بنویس.",
            "items": [
                {"prompt": "Jag har ingen bil så jag ___ till jobbet.", "answer": "går"},
                {"prompt": "Nästa sommar ska vi ___ till Nya Zeeland.", "answer": "åka"},
                {"prompt": "Magnus brukar cykla till kursen men igår ___ han bil.", "answer": "åkte"},
                {"prompt": "Båten till Gotland ___ om en kvart.", "answer": "går"},
                {"prompt": "Bussen ___ för fem minuter sedan.", "answer": "gick"},
            ],
        },
        {
            "num": 12, "title": "Prepositioner", "type": "fill",
            "instructions": "حرف اضافه‌ی درست رو بنویس.",
            "items": [
                {"prompt": "Fiona pluggar ___ Umeå.", "answer": "i"},
                {"prompt": "Marie bor ___ Kyrkgatan.", "answer": "på"},
                {"prompt": "Henrik brukar vara ___ Dalarna på somrarna.", "answer": "i"},
                {"prompt": "Juan har ett hus ___ Öland.", "answer": "på"},
                {"prompt": "Ulrika är ___ jobbet.", "answer": "på"},
            ],
        },
        {
            "num": 13, "title": "Verb: preteritum eller presens perfekt", "type": "fill",
            "instructions": "شکل مناسب فعل رو بنویس.",
            "items": [
                {"prompt": "I vintras ___ (har vi åkt / åkte vi) till Chamonix.", "answer": "åkte vi"},
                {"prompt": "Åh, vad härligt! Jag ___ (har aldrig varit / var aldrig) där.", "answer": "har aldrig varit"},
                {"prompt": "När ___ (har du gift / gifte du) dig med farmor?", "answer": "gifte du"},
                {"prompt": "Det ___ (har varit / var) 1954,", "answer": "var"},
                {"prompt": "så vi ___ (har varit / var) gifta i 60 år nu.", "answer": "har varit"},
                {"prompt": "___ (Har du hoppat / Hoppade du) fallskärm någon gång? – Nej, aldrig.", "answer": "Har du hoppat"},
            ],
        },
        {
            "num": 14, "title": "Siffror som substantiv", "type": "fill",
            "instructions": "شکل درست عدد رو بنویس (مثال: 5 → femman).",
            "items": [
                {"prompt": "Passar skorna bra? – Nja, de är lite för stora. Har ni några ___ (37)?", "answer": "trettiosjuor"},
                {"prompt": "Vilken buss ska vi ta? – Vi tar ___ (3). Det går snabbast.", "answer": "trean"},
                {"prompt": "Jag behöver lite mer pengar till automaten. Har du några ___ (10)?", "answer": "tior"},
                {"prompt": "Vilken klass går din dotter i? – Hon går i ___ (9).", "answer": "nian"},
                {"prompt": "Hur stor lägenhet har ni? – Vi bor i en ___ (5).", "answer": "femma"},
            ],
        },
    ],
}

FRAMSTEGSTEST_4 = {
    "title": "Framstegstest 4",
    "subtitle": "فصل ۱۱ تا ۱۳",
    "sections": [
        {
            "num": 1, "title": "Vad svarar man?", "type": "mcq",
            "instructions": "جواب مناسب رو انتخاب کن.",
            "items": [
                {"prompt": "Jag tycker inte om broccoli.",
                 "options": ["Inte jag heller.", "Jag också.", "Men det gör inte jag."], "correct": 0},
                {"prompt": "Jag tror att du ville bli polis när du var liten.",
                 "options": ["Ja, det tror jag.", "Ja, det tycker jag.", "Ja, det stämmer."], "correct": 2},
                {"prompt": "Jag älskar kanelbullar!",
                 "options": ["Inte jag heller.", "Jag också.", "Men det gör jag."], "correct": 1},
                {"prompt": "Oj, jag skrev fel!",
                 "options": ["Ja, det går bra.", "Bra idé!", "Ingen fara."], "correct": 2},
                {"prompt": "Vi kanske ska betala?",
                 "options": ["Ja. Ursäkta, kan vi få menyn?", "Ja. Ursäkta, kan vi få notan?",
                             "Ja. Ursäkta, kan vi beställa?"], "correct": 1},
                {"prompt": "Smakade det bra?",
                 "options": ["Ja, det var gott.", "Ja, det var roligt.", "Ja, det var trevligt."], "correct": 0},
                {"prompt": "Är det inte förbjudet att ladda ner filmer?",
                 "options": ["Ja.", "Jaha.", "Jo."], "correct": 2},
                {"prompt": "Jag tycker att Lasse borde söka jobbet som tennislärare.",
                 "options": ["Det tycker inte jag heller.", "Jag håller med.", "Jo, det tycker jag."], "correct": 1},
                {"prompt": "Vad är det här för kabel?",
                 "options": ["Du kan koppla scannern till datorn med den.", "Du kan stoppa in scannern till datorn med den.",
                             "Du kan sätta på scannern till datorn med den."], "correct": 0},
                {"prompt": "Skrivaren fungerar inte.",
                 "options": ["Du kanske måste sätta på papper.", "Du kanske måste fylla på papper.",
                             "Du kanske måste skriva ut papper."], "correct": 1},
            ],
        },
        {
            "num": 2, "title": "Konjunktioner", "type": "fill",
            "instructions": "کلمه‌ی ربط مناسب رو از این‌ها بنویس: eller, men, för, och, så.",
            "items": [
                {"prompt": "Jag är jättetrött ___ jag går och lägger mig nu.", "answer": "så"},
                {"prompt": "Petter pratar bra franska ___ han talar inte engelska.", "answer": "men"},
                {"prompt": "Ska vi äta middag hemma ___ ska vi gå på restaurang?", "answer": "eller"},
                {"prompt": "Jag måste gå hem och plugga ___ jag har ett stort prov imorgon.", "answer": "för"},
                {"prompt": "Ska vi gå på kafé ___ fika?", "answer": "och"},
                {"prompt": "Bilen startade inte i morse ___ jag tog bussen till jobbet.", "answer": "så"},
                {"prompt": "Jag skulle vilja gå ut ikväll ___ jag har inga pengar.", "answer": "men"},
                {"prompt": "Jag går och lägger mig nu ___ jag är jättetrött.", "answer": "för"},
            ],
        },
        {
            "num": 3, "title": "Ordföljd: samordning", "type": "fill",
            "instructions": "جمله رو با کلمه‌ی داخل پرانتز کامل کن و لازم اگه بود فاعل بنویس.",
            "items": [
                {"prompt": "Filmen jag såg var ganska tråkig så efter en kvart ___ . (somnade)", "answer": "somnade jag"},
                {"prompt": "Jag måste handla och sedan ___ . (ska laga mat)", "answer": "ska jag laga mat"},
                {"prompt": "Jag måste plugga men först ___ . (ska gå på gym)", "answer": "ska jag gå på gym"},
            ],
        },
        {
            "num": 4, "title": "Substantiv: bestämd eller obestämd form?", "type": "mcq",
            "instructions": "گزینه‌ی درست رو انتخاب کن.",
            "items": [
                {"prompt": "Maria, kan du stänga av ...?", "options": ["teve", "teven"], "correct": 1},
                {"prompt": "Fredriks ... är jättefina.", "options": ["hundar", "hundarna"], "correct": 0},
                {"prompt": "Vi tittade på ett hus igår. ... var ganska liten.", "options": ["Trädgården", "Trädgård"], "correct": 0},
                {"prompt": "Gustav spelar ...", "options": ["saxofon.", "saxofonen."], "correct": 0},
                {"prompt": "De här ... var billiga.", "options": ["byxor", "byxorna"], "correct": 1},
                {"prompt": "Anneli och jag satt på kafé och diskuterade ... i lördags.", "options": ["liv", "livet"], "correct": 1},
                {"prompt": "Vad brukar du göra på ...?", "options": ["helger", "helgerna"], "correct": 1},
                {"prompt": "Nästa ... har vi ett stort prov.", "options": ["vecka", "veckan"], "correct": 0},
                {"prompt": "Vi var på teater igår. ... var helt fantastiska.", "options": ["Skådespelarna", "Skådespelare"], "correct": 0},
                {"prompt": "Har du träffat Elsas ...?", "options": ["pojkvän", "pojkvännen"], "correct": 0},
            ],
        },
        {
            "num": 5, "title": "Få, många, lite, mycket", "type": "fill",
            "instructions": "کلمه‌ی مناسب رو از این‌ها بنویس: få, många, lite, mycket.",
            "items": [
                {"prompt": "Hur ___ mjölk har vi hemma? – Nästan en liter.", "answer": "mycket"},
                {"prompt": "Jag har ___ vänner som tränar på gym, så jag tränar nästan alltid ensam.", "answer": "få"},
                {"prompt": "Hur ___ gånger har du varit på Öland? – Tio, tror jag.", "answer": "många"},
                {"prompt": "Dricker du ___ kaffe?", "answer": "mycket"},
                {"prompt": "Nej, ganska ___ faktiskt. En kopp varannan dag ungefär.", "answer": "lite"},
            ],
        },
        {
            "num": 6, "title": "Partikelverb", "type": "fill",
            "instructions": "پارتیکل درست رو بنویس.",
            "items": [
                {"prompt": "Kan du sätta ___ radion? Jag vill lyssna på ett program som börjar nu.", "answer": "på"},
                {"prompt": "Det är något fel på min dator. Jag har startat ___ den, men den fungerar ändå inte.", "answer": "om"},
                {"prompt": "Jag behöver skriva ___ ett dokument, men pappret är slut.", "answer": "ut"},
                {"prompt": "Nu måste du stänga ___ teven och gå och lägga dig, Maja.", "answer": "av"},
                {"prompt": "Oj, är klockan tio? Då måste jag gå ___ med hunden.", "answer": "ut"},
            ],
        },
        {
            "num": 7, "title": "Tror/tycker", "type": "fill",
            "instructions": "tror یا tycker — کدوم مناسبه؟",
            "items": [
                {"prompt": "Är Restaurang Lyxlaxen bra? – Maten är god men jag ___ att det är lite för dyrt.", "answer": "tycker"},
                {"prompt": "När börjar mötet? – Jag är inte säker, men jag ___ att det är klockan två.", "answer": "tror"},
                {"prompt": "Har du ätit kräftor? – Nej, men jag ___ att det är gott.", "answer": "tror"},
                {"prompt": "Har du varit i Umeå någon gång? – O ja, många gånger. Jag ___ att det är jättevackert där!", "answer": "tycker"},
                {"prompt": "Jag ___ att den här tavlan är så vacker! – Ja, verkligen.", "answer": "tycker"},
            ],
        },
        {
            "num": 8, "title": "Subjunktioner", "type": "fill",
            "instructions": "کلمه‌ی مناسب رو از این‌ها بنویس: eftersom, när, om, att.",
            "items": [
                {"prompt": "___ solen skiner imorgon kan vi ha picknick.", "answer": "Om"},
                {"prompt": "Jag måste plugga ___ jag kommer hem.", "answer": "när"},
                {"prompt": "Joel säger ___ mötet börjar klockan ett.", "answer": "att"},
                {"prompt": "Vi kan gå på bio ikväll ___ du vill.", "answer": "om"},
                {"prompt": "Jag går och lägger mig nu ___ jag är så trött.", "answer": "eftersom"},
                {"prompt": "Anne tycker ___ sill är gott.", "answer": "att"},
                {"prompt": "Lars lyssnar alltid på radio ___ han äter frukost.", "answer": "när"},
                {"prompt": "Vi gick inte ut igår ___ det regnade hela dagen.", "answer": "eftersom"},
            ],
        },
        {
            "num": 9, "title": "Ordföljd: bisats", "type": "fill",
            "instructions": "کلمات پخش‌شده رو مرتب کن و جمله‌ی کامل بساز.",
            "items": [
                {"prompt": "Kan du väcka mig ___? (sju / när / är / klockan)",
                 "answer": "Kan du väcka mig när klockan är sju?"},
                {"prompt": "Jag gick hem från jobbet ___ . (mådde / så bra / eftersom / inte / jag)",
                 "answer": "Jag gick hem från jobbet eftersom jag inte mådde så bra."},
                {"prompt": "Gösta säger ___ . (tennis / ofta / han / att / spelar)",
                 "answer": "Gösta säger att han ofta spelar tennis."},
                {"prompt": "Vi kan stanna hemma ___ . (du / ut / om / vill / inte / gå)",
                 "answer": "Vi kan stanna hemma om du inte vill gå ut."},
                {"prompt": "Sam pratar engelska med mig ___ . (svenska / eftersom / inte / kan / han)",
                 "answer": "Sam pratar engelska med mig eftersom han inte kan svenska."},
            ],
        },
        {
            "num": 10, "title": "Nationalitetsadjektiv", "type": "fill",
            "instructions": "صفت ملیت درست رو بنویس (en yoghurt, ett vin, ett te, en musik).",
            "items": [
                {"prompt": "Kan du köpa ___ (Turkiet) yoghurt när du handlar?", "answer": "turkisk"},
                {"prompt": "Thomas dricker ofta ___ (Spanien) vin.", "answer": "spanskt"},
                {"prompt": "Vet du några bra ___ (Korea) restauranger?", "answer": "koreanska"},
                {"prompt": "Vill du ha ___ (Japan) te?", "answer": "japanskt"},
                {"prompt": "Christina har många ___ (Danmark) vänner.", "answer": "danska"},
                {"prompt": "Nils tycker mycket om ___ (Brasilien) musik.", "answer": "brasiliansk"},
            ],
        },
        {
            "num": 11, "title": "Sitter och, ligger och, står och", "type": "fill",
            "instructions": "sitter, står یا ligger رو در شکل مناسب بنویس.",
            "items": [
                {"prompt": "Lovisa, nu har du ___ och chattat framför datorn i fyra timmar. Stäng av nu!", "answer": "suttit"},
                {"prompt": "Är mormor vaken? – Nej, hon ___ och sover.", "answer": "ligger"},
                {"prompt": "Var är Bengt? – Han ___ och diskar i köket.", "answer": "står"},
                {"prompt": "Nu har du ___ och solat i gräset länge. Du borde ha solkräm.", "answer": "legat"},
            ],
        },
        {
            "num": 12, "title": "Ordföljd: bisats + huvudsats", "type": "fill",
            "instructions": "کلمات رو مرتب کن. با کلمه‌ی پررنگ شروع کن.",
            "items": [
                {"prompt": "Eftersom/skiner/solen + bada/idag/vi/kan", "answer": "Eftersom solen skiner kan vi bada idag."},
                {"prompt": "Om/vill/på teater/inte/du/gå + på bio/kan/i stället/gå/vi",
                 "answer": "Om du inte vill gå på teater kan vi gå på bio i stället."},
                {"prompt": "Eftersom/varje dag/repeterar/jag + nu/alla verb/jag/kan",
                 "answer": "Eftersom jag repeterar varje dag kan jag alla verb nu."},
                {"prompt": "Om/börjar/regna/det + vi/in/går", "answer": "Om det börjar regna går vi in."},
                {"prompt": "Eftersom/inte/kom/bussen + vi/till museet/promenerade",
                 "answer": "Eftersom bussen inte kom promenerade vi till museet."},
            ],
        },
        {
            "num": 13, "title": "Yrken", "type": "fill",
            "instructions": "این شغل‌ها با چه کلمه‌ای مرتبطن؟ (sjukhus, turister, bollar, hus, blommor, färg, gym)",
            "items": [
                {"prompt": "trädgårdsmästare", "answer": "blommor"},
                {"prompt": "personlig tränare", "answer": "gym"},
                {"prompt": "sjuksköterska", "answer": "sjukhus"},
                {"prompt": "tennislärare", "answer": "bollar"},
                {"prompt": "guide", "answer": "turister"},
                {"prompt": "arkitekt", "answer": "hus"},
                {"prompt": "målare", "answer": "färg"},
            ],
        },
        {
            "num": 14, "title": "Adverb", "type": "fill",
            "instructions": "قید مکان مناسب رو از گزینه‌های داده‌شده بنویس.",
            "items": [
                {"prompt": "Ursäkta, hur går jag ___ (här/hit/härifrån) till Hotell Viking?", "answer": "härifrån"},
                {"prompt": "Det är ganska långt, men du kan ta bussen ___ (där/dit/därifrån).", "answer": "dit"},
                {"prompt": "(på telefon) Sara, jag väntar på dig på kaféet. Kommer du ___ (här/hit/härifrån) snart?", "answer": "hit"},
                {"prompt": "Jag går ___ (hemma/hem/hemifrån) nu, så jag kommer om fem minuter!", "answer": "hemifrån"},
                {"prompt": "Titta, ___ (där/dit/därifrån) sitter Sam och Linda.", "answer": "där"},
                {"prompt": "Ska vi gå ___ (där/dit/därifrån) och hälsa på dem?", "answer": "dit"},
                {"prompt": "(ett sms) Hej pappa! Nu är jag ___ (uppe/upp/uppifrån) i Empire State Building.", "answer": "uppe"},
                {"prompt": "Här ___ (uppe/upp/uppifrån) ser jag hela Manhattan!", "answer": "uppifrån"},
            ],
        },
        {
            "num": 15, "title": "Verb: tempus", "type": "fill",
            "instructions": "preteritum یا presens perfekt — کدوم مناسبه؟",
            "items": [
                {"prompt": "Emil ___ (slutade/har slutat) skolan förra året.", "answer": "slutade"},
                {"prompt": "När ___ (kom du/har du kommit) till Sverige?", "answer": "kom du"},
                {"prompt": "Fanny ___ (jobbade/har jobbat) på IT-Direkt i tio år nu.", "answer": "har jobbat"},
                {"prompt": "Hur många gånger ___ (var du/har du varit) i Rom?", "answer": "har du varit"},
                {"prompt": "Ludvig ___ (vaknade/har vaknat) vid elva i morse.", "answer": "vaknade"},
                {"prompt": "Miles ___ (pluggade/har pluggat) mycket i år.", "answer": "har pluggat"},
                {"prompt": "Filmen ___ (började/har börjat) för fem minuter sedan.", "answer": "började"},
            ],
        },
        {
            "num": 16, "title": "Infinitiv med att och utan att", "type": "mcq",
            "instructions": "گزینه‌ی درست رو انتخاب کن.",
            "items": [
                {"prompt": "1", "options": ["Jag behöver att hjälpa mamma på söndag.", "Jag behöver hjälpa mamma på söndag."], "correct": 1},
                {"prompt": "2", "options": ["Oscar gillar att laga mat.", "Oscar gillar laga mat."], "correct": 0},
                {"prompt": "3", "options": ["Kicki är bra på att måla.", "Kicki är bra på måla."], "correct": 0},
                {"prompt": "4", "options": ["Daniel brukar att träna varje dag.", "Daniel brukar träna varje dag."], "correct": 1},
            ],
        },
    ],
}

FRAMSTEGSTEST_5 = {
    "title": "Framstegstest 5",
    "subtitle": "فصل ۱۴ تا ۱۶",
    "sections": [
        {
            "num": 1, "title": "Vad svarar man?", "type": "mcq",
            "instructions": "جواب مناسب رو انتخاب کن.",
            "items": [
                {"prompt": "Vill ni inte komma ut till oss på landet i helgen?",
                 "options": ["Ja, gärna.", "Ja, tack.", "Jo, gärna."], "correct": 2},
                {"prompt": "Vad gott det var!", "options": ["Ja, tack.", "Ja, verkligen.", "Varsågod."], "correct": 1},
                {"prompt": "Ta mer om ni vill ha!",
                 "options": ["Det är bra för mig, tack.", "Ja, verkligen.", "Tack själv."], "correct": 0},
                {"prompt": "Vad fin du är!", "options": ["Tycker du? Tack!", "Det är bra för mig, tack.", "Ja, tack."], "correct": 0},
                {"prompt": "Det var någon som sökte dig förut.",
                 "options": ["Jaha, vad då?", "Jaha, hur många då?", "Jaha, vem då?"], "correct": 2},
            ],
        },
        {
            "num": 2, "title": "Ord och fraser", "type": "mcq",
            "instructions": "جمله چه معنایی داره؟",
            "items": [
                {"prompt": "Richard hoppade av skolan.",
                 "options": ["Han gick ett extra år i skolan.", "Han började skolan.", "Han slutade skolan."], "correct": 2},
                {"prompt": "Petra skolkar ibland.",
                 "options": ["Hon går inte till skolan ibland.", "Hon pluggar extra ibland.",
                             "Hon kommer för sent till skolan ibland."], "correct": 0},
                {"prompt": "Filip trivs i skolan.",
                 "options": ["Han vill sluta skolan.", "Han tycker om att gå i skolan.",
                             "Han tycker inte om att gå i skolan."], "correct": 1},
                {"prompt": "Magda är en plugghäst.",
                 "options": ["Hon går sällan till skolan.", "Hon gör aldrig sina läxor.", "Hon studerar mycket."], "correct": 2},
                {"prompt": "Simon pluggar på komvux.",
                 "options": ["Han går på ett gymnasium för vuxna.", "Han går på högskolan.", "Han går i grundskolan."], "correct": 0},
                {"prompt": "Karl ska ha en föreläsning på universitetet idag.",
                 "options": ["Han ska diskutera med studenterna.", "Han ska ha en lektion för studenterna.",
                             "Han ska bedöma studenterna."], "correct": 1},
                {"prompt": "I skolan läser man olika ämnen …",
                 "options": ["… från A-F.", "… klass 1–9.", "… till exempel matematik och historia."], "correct": 2},
                {"prompt": "Sofia har inte så bra betyg i matte.",
                 "options": ["Hon har A.", "Hon har E.", "Matte är hennes favoritämne."], "correct": 1},
            ],
        },
        {
            "num": 3, "title": "Ordföljd: indirekt tal", "type": "fill",
            "instructions": "جمله رو به indirekt tal (نقل‌قول غیرمستقیم) تبدیل کن.",
            "items": [
                {"prompt": "Nils: När börjar föreläsningen?", "answer": "Nils frågar/undrar när föreläsningen börjar.",
                 "accept": ["Nils frågar när föreläsningen börjar.", "Nils undrar när föreläsningen börjar."]},
                {"prompt": "Anders: Jag tycker inte om kött.", "answer": "Anders säger att han inte tycker om kött."},
                {"prompt": "Pia: Har de bra mat på Lyxlaxen?", "answer": "Pia frågar/undrar om de har bra mat på Lyxlaxen.",
                 "accept": ["Pia frågar om de har bra mat på Lyxlaxen.", "Pia undrar om de har bra mat på Lyxlaxen."]},
                {"prompt": "Daniel: Jag förstår inte.", "answer": "Daniel säger att han inte förstår."},
                {"prompt": "Claudia: Varför kommer aldrig bussen?",
                 "answer": "Claudia frågar/undrar varför bussen aldrig kommer.",
                 "accept": ["Claudia frågar varför bussen aldrig kommer.", "Claudia undrar varför bussen aldrig kommer."]},
            ],
        },
        {
            "num": 4, "title": "Verb", "type": "fill",
            "instructions": "فعل مناسب از این‌ها رو انتخاب و با شکل درست بنویس: klippa, skina, bråka, måla, spela, tända, plocka, hugga.",
            "passage": (
                "I somras var vi på landet hela semestern. Solen ___(1)___ nästan varje dag. Vi ___(2)___ "
                "blåbär, badade och ___(3)___ kort med barnen. Ibland ___(4)___ vi med varandra. Gustav "
                "kan bli väldigt arg när han inte vinner. På kvällen ___(5)___ vi grillen. Vi grillade "
                "ofta. Men vi hade en del arbete också. Varje vecka ___(6)___ vi gräset och en helg "
                "___(7)___ vi en massa ved. Och i början av semestern ___(8)___ vi huset. Det blev jättefint!"
            ),
            "items": [
                {"prompt": "(1)", "answer": "sken"}, {"prompt": "(2)", "answer": "plockade"},
                {"prompt": "(3)", "answer": "spelade"}, {"prompt": "(4)", "answer": "bråkade"},
                {"prompt": "(5)", "answer": "tände"}, {"prompt": "(6)", "answer": "klippte"},
                {"prompt": "(7)", "answer": "högg"}, {"prompt": "(8)", "answer": "målade"},
            ],
        },
        {
            "num": 5, "title": "Ordföljd: bisats + huvudsats", "type": "fill",
            "instructions": "جمله رو جوری بازنویسی کن که بیساتس اول بیاد.",
            "items": [
                {"prompt": "Jag vill inte gå ut eftersom det är så kallt idag. → Eftersom ___ .",
                 "answer": "Eftersom det är så kallt idag vill jag inte gå ut."},
                {"prompt": "Du måste fråga om du inte förstår. → Om ___ .",
                 "answer": "Om du inte förstår måste du fråga."},
                {"prompt": "Nils orkar inte svara när telefonen ringer. → När ___ .",
                 "answer": "När telefonen ringer orkar Nils inte svara.",
                 "accept": ["När telefonen ringer orkar inte Nils svara."]},
                {"prompt": "Jag ska köpa en ny dator trots att jag inte har så mycket pengar. → Trots att ___ .",
                 "answer": "Trots att jag inte har så mycket pengar ska jag köpa en ny dator."},
            ],
        },
        {
            "num": 6, "title": "Självständiga pronomen", "type": "fill",
            "instructions": "کلمه‌ی مناسب رو از این‌ها بنویس: någon, alla, inget, något, ingen.",
            "items": [
                {"prompt": "Det var en jättetrevlig kväll. ___ var så glada och roliga.", "answer": "Alla"},
                {"prompt": "Jag gick hem till Perssons igår, men ___ var hemma. De var kanske på landet.", "answer": "ingen"},
                {"prompt": "Igår var Tove på stan för att shoppa, men hon köpte ___ .", "answer": "inget"},
                {"prompt": "Arne känner sig så ledsen och han har inte ___ att prata med.", "answer": "någon"},
                {"prompt": "Jag tycker att det här är svårt. Förstår du ___?", "answer": "något"},
            ],
        },
        {
            "num": 7, "title": "Subjunktioner", "type": "fill",
            "instructions": "کلمه‌ی مناسب رو از این‌ها بنویس: innan, medan, även om, trots att, utan att, genom att, för att.",
            "items": [
                {"prompt": "Jag kan inte förstå tyska filmer ___ läsa texten.", "answer": "utan att"},
                {"prompt": "Du kan lära dig mycket ___ repetera ofta.", "answer": "genom att"},
                {"prompt": "Christina ska bada idag ___ det är så kallt ute.", "answer": "trots att"},
                {"prompt": "Stella och Alma åker till stan ___ shoppa kläder.", "answer": "för att"},
                {"prompt": "Jonas promenerar en timme varje dag ___ det är dåligt väder.", "answer": "även om"},
                {"prompt": "Jag måste bara diska ___ vi går ut.", "answer": "innan"},
                {"prompt": "Nils tar en tupplur ___ hans sambo duschar.", "answer": "medan"},
            ],
        },
        {
            "num": 8, "title": "Possessiva och reflexiva possessiva pronomen", "type": "fill",
            "instructions": "sin/sitt/sina یا hans/hennes/deras — کدوم مناسبه؟",
            "items": [
                {"prompt": "Oscar pratar med ___ mormor varje dag.", "answer": "sin"},
                {"prompt": "___ mormor är 95 år.", "answer": "Hans"},
                {"prompt": "På sommaren åker Ellen och ___ sambo till landet.", "answer": "hennes"},
                {"prompt": "Ann går ut med ___ hundar fyra gånger om dagen.", "answer": "sina"},
                {"prompt": "___ hundar heter Sally och George.", "answer": "Hennes"},
                {"prompt": "Dan jobbar på en advokatfirma. ___ chef är engelsman.", "answer": "Hans"},
                {"prompt": "Mats, Johanna och alla ___ barn åker till Oslo imorgon.", "answer": "deras"},
                {"prompt": "Kurt-Allan och Berit ska måla ___ hus i sommar.", "answer": "sitt"},
            ],
        },
        {
            "num": 9, "title": "Först, då, sedan", "type": "fill",
            "instructions": "کلمه‌ی مناسب رو از این‌ها بنویس: först, då, sedan.",
            "items": [
                {"prompt": "Stina kom hem från jobbet klockan sju igår. ___ var hon jättetrött.", "answer": "Då"},
                {"prompt": "Joel ska gå ut ikväll, men ___ måste han ringa mamma.", "answer": "först"},
                {"prompt": "Mötet börjar två prick. ___ måste alla vara här.", "answer": "Då"},
                {"prompt": "Nu ska jag plugga. ___ ska jag gå till gymmet och träna.", "answer": "Sedan"},
                {"prompt": "Kim ska åka till stan, men ___ ska hon ta en dusch.", "answer": "först"},
            ],
        },
        {
            "num": 10, "title": "Presens futurum", "type": "fill",
            "instructions": "ska یا kommer att — کدوم مناسبه؟",
            "items": [
                {"prompt": "Jag tror att det ___ bli en fin sommar.", "answer": "kommer att"},
                {"prompt": "Hoppas! Jag ___ bada varje dag i så fall.", "answer": "ska"},
                {"prompt": "Jag ___ börja plugga teknisk fysik i höst.", "answer": "ska"},
                {"prompt": "Oj. Tror du att det ___ bli tufft?", "answer": "kommer att"},
                {"prompt": "Vi har ett stort prov på måndag, så jag ___ plugga hela helgen. Jag är lite nervös.", "answer": "ska"},
                {"prompt": "Det ___ att gå bra.", "answer": "kommer"},
            ],
        },
        {
            "num": 11, "title": "Relativa pronomen", "type": "fill",
            "instructions": "där, som یا när — کدوم مناسبه؟",
            "items": [
                {"prompt": "På morgonen ___ jag vaknar är jag alltid jättetrött.", "answer": "när"},
                {"prompt": "Vet du någon restaurang ___ de har svensk mat?", "answer": "där"},
                {"prompt": "Jag har en kompis ___ pratar thailändska.", "answer": "som"},
                {"prompt": "Kontoret ___ jag jobbar ligger mitt i stan.", "answer": "där"},
                {"prompt": "Jag älskar filmer ___ är romantiska.", "answer": "som"},
            ],
        },
        {
            "num": 12, "title": "Relativa bisatser", "type": "fill",
            "instructions": "کلمات پخش‌شده رو مرتب کن.",
            "items": [
                {"prompt": "Ludvig har en kusin ___ . (ofta / han / med / som / pratar)", "answer": "som han ofta pratar med."},
                {"prompt": "Fia har tittat på en lägenhet ___ . (köpa / som / kanske / ska / hon)",
                 "answer": "som hon kanske ska köpa."},
                {"prompt": "Max har en klasskompis ___ . (lärarens frågor / kan / alltid / som / på / svara)",
                 "answer": "som alltid kan svara på lärarens frågor."},
                {"prompt": "Patrik har en kollega ___ . (brukar / som / äta / till lunch / alltid / en smörgås)",
                 "answer": "som alltid brukar äta en smörgås till lunch."},
            ],
        },
        {
            "num": 13, "title": "Prepositioner", "type": "fill",
            "instructions": "حرف اضافه‌ی درست رو بنویس.",
            "items": [
                {"prompt": "Simon och Matilda har alltid drömt ___ att ha en stuga", "answer": "om"},
                {"prompt": "... ___ landet.", "answer": "på"},
                {"prompt": "Kajsa är inte rädd ___ hundar,", "answer": "för"},
                {"prompt": "men hon har respekt ___ dem.", "answer": "för"},
                {"prompt": "Anita och Ralf bodde ___ skärgården", "answer": "i"},
                {"prompt": "___ 90-talet. De hade ett hus precis", "answer": "på"},
                {"prompt": "___ havet.", "answer": "vid"},
                {"prompt": "Vi är bjudna ___ en grillfest", "answer": "på"},
                {"prompt": "___ familjen Wikman", "answer": "hos", "accept": ["till"]},
                {"prompt": "___ lördag.", "answer": "på"},
            ],
        },
        {
            "num": 14, "title": "Verb i grupp 4", "type": "fill",
            "instructions": "شکلی که کمه رو از جدول بنویس (bli, göra, ha, komma, se).",
            "items": [
                {"prompt": "bli — Infinitiv (امر: bli!)", "answer": "bli"},
                {"prompt": "bli — Presens", "answer": "blir"},
                {"prompt": "bli — Preteritum", "answer": "blev"},
                {"prompt": "bli — Supinum", "answer": "blivit"},
                {"prompt": "göra — Imperativ (اینفینیتیو: göra)", "answer": "gör!"},
                {"prompt": "göra — Presens", "answer": "gör"},
                {"prompt": "göra — Preteritum", "answer": "gjorde"},
                {"prompt": "göra — Supinum", "answer": "gjort"},
                {"prompt": "ha — Imperativ (حال: har)", "answer": "ha!"},
                {"prompt": "ha — Infinitiv", "answer": "ha"},
                {"prompt": "ha — Preteritum", "answer": "hade"},
                {"prompt": "ha — Supinum", "answer": "haft"},
                {"prompt": "komma — Imperativ (preteritum: kom)", "answer": "kom!"},
                {"prompt": "komma — Infinitiv", "answer": "komma"},
                {"prompt": "komma — Presens", "answer": "kommer"},
                {"prompt": "komma — Supinum", "answer": "kommit"},
                {"prompt": "se — Imperativ (supinum: sett)", "answer": "se!"},
                {"prompt": "se — Infinitiv", "answer": "se"},
                {"prompt": "se — Presens", "answer": "ser"},
                {"prompt": "se — Preteritum", "answer": "såg"},
            ],
        },
    ],
}

FRAMSTEGSTEST_6 = {
    "title": "Framstegstest 6",
    "subtitle": "فصل ۱۷ تا ۱۹",
    "sections": [
        {
            "num": 1, "title": "Vad svarar man?", "type": "mcq",
            "instructions": "جواب مناسب رو انتخاب کن.",
            "items": [
                {"prompt": "Gunilla sitter i telefon. Vill du vänta?",
                 "options": ["Det ska jag göra.", "Ett ögonblick.", "Nej, tack. Jag återkommer."], "correct": 2},
                {"prompt": "Tack och hej.", "options": ["Hej då.", "Okej.", "Nej, men hej."], "correct": 0},
                {"prompt": "Oj ursäkta, då har jag ringt fel.",
                 "options": ["Var god dröj.", "Ingen fara.", "Nej, tack."], "correct": 1},
                {"prompt": "Kan jag ta ett meddelande?",
                 "options": ["Ja, be Karina ringa mig.", "Det ska jag göra.", "Då säger vi så."], "correct": 0},
                {"prompt": "Jag söker Pia Andersson.",
                 "options": ["Det ska jag göra.", "Då så.", "Ett ögonblick."], "correct": 2},
                {"prompt": "Hur mår du?", "options": ["Ja, det gör jätteont!", "Ja, lite.", "Så där."], "correct": 2},
                {"prompt": "Jag måste gå hem för jag har så ont i huvudet.",
                 "options": ["Stackare. Krya på dig!", "Oj, tyvärr.", "Det låter härligt."], "correct": 0},
                {"prompt": "Jag hostar så mycket.",
                 "options": ["Här, ta en huvudvärkstablett.", "Kommer det upp slem också?", "Aj! Ja, det gör jätteont."], "correct": 1},
                {"prompt": "Är du yr?", "options": ["Ja, jag måste sätta mig.", "Ja, lite. 38,0.", "Ja, det gör ont."], "correct": 0},
                {"prompt": "Mår du illa?",
                 "options": ["Ja, jag tror att jag måste gå till tandläkaren.", "Ja, jag tror att jag måste kräkas.",
                             "Ja, jag tror att jag måste svettas."], "correct": 1},
            ],
        },
        {
            "num": 2, "title": "Verb", "type": "fill",
            "instructions": "فعل مناسب از این‌ها رو انتخاب و با شکل درست بنویس: flytta, hälla, fylla, gå, sätta, beställa, trycka, stå, tjäna, känna, lära, ligga.",
            "items": [
                {"prompt": "Titta, det ___ i tidningen att det ska bli regn imorgon.", "answer": "står"},
                {"prompt": "Jag skulle vilja ___ tid för klippning hos Acke.", "answer": "beställa"},
                {"prompt": "Nisse har köpt en lägenhet och ska ___ hemifrån nu.", "answer": "flytta"},
                {"prompt": "Daniela tryckte in fel kod, så larmet ___ .", "answer": "gick"},
                {"prompt": "Restaurang Glada Älgen ___ på Krutgatan, så vi kan promenera dit.", "answer": "ligger"},
                {"prompt": "___ på den här knappen om du vill kopiera dubbelsidigt!", "answer": "Tryck"},
                {"prompt": "När Isa var sju år ___ hon sig att spela trummor.", "answer": "lärde"},
                {"prompt": "Har du ___ på papper i kopieringsmaskinen?", "answer": "fyllt"},
                {"prompt": "Kan du ___ på teven? Jag vill se ett program som börjar nu.", "answer": "sätta"},
                {"prompt": "Olof har alltid ___ sig lite utanför. Han har inte så många kompisar.", "answer": "känt"},
                {"prompt": "Sylvia ___ mycket pengar när hon jobbade som IT-konsult.", "answer": "tjänade"},
                {"prompt": "När du gör kaffe ska du ___ i vatten upp till den här markeringen.", "answer": "hälla"},
            ],
        },
        {
            "num": 3, "title": "Kortsvar", "type": "fill",
            "instructions": "با kortsvar (پاسخ کوتاه) جواب بده.",
            "items": [
                {"prompt": "Har Nina syskon? – Ja, ___ .", "answer": "det har hon"},
                {"prompt": "Snusar Lars? – Nej, ___ .", "answer": "det gör han inte"},
                {"prompt": "Kommer inte Dean från Nya Zeeland? – Jo, ___ .", "answer": "det gör han"},
                {"prompt": "Är du nöjd med resultatet? – Ja, ___ .", "answer": "det är jag"},
                {"prompt": "Kan Jonas och Åsa dansa tango? – Nej, ___ .", "answer": "det kan de inte"},
            ],
        },
        {
            "num": 4, "title": "Komparation", "type": "fill",
            "instructions": "شکل درست صفت/قید رو بنویس.",
            "items": [
                {"prompt": "Sofi har ___ fötter än Linda. (liten)", "answer": "mindre"},
                {"prompt": "Gösta bor ___ stan än vi. (nära)", "answer": "närmare"},
                {"prompt": "Deras båtar är lika ___ . (snabb)", "answer": "snabba"},
                {"prompt": "Anton är ___ av alla bröder. (lång)", "answer": "längst"},
                {"prompt": "Helen äter ___ fisk än kött. (gärna)", "answer": "hellre"},
                {"prompt": "Vem är ___, morfar eller farfar? (gammal)", "answer": "äldst"},
                {"prompt": "Sanna pratar ___ franska än engelska. (bra)", "answer": "bättre"},
                {"prompt": "John är ___ av film än litteratur. (intresserad)", "answer": "mer intresserad"},
                {"prompt": "Anna pratar ___ av alla barn i klassen. (mycket)", "answer": "mest"},
                {"prompt": "Robin är ___ än Sam. (ung)", "answer": "yngre"},
            ],
        },
        {
            "num": 5, "title": "Sitta/ligga/stå och rumsprepositioner", "type": "fill",
            "instructions": "sitter/ligger/står + حرف اضافه‌ی مناسب رو بنویس (تصویر اتاق خواب به‌هم‌ریخته).",
            "items": [
                {"prompt": "Kaffekoppen ___ (فعل)", "answer": "står"},
                {"prompt": "Kaffekoppen står ___ (حرف اضافه) sängbordet.", "answer": "på"},
                {"prompt": "Lamporna ___ (فعل)", "answer": "sitter"},
                {"prompt": "Lamporna sitter ___ (حرف اضافه) väggen.", "answer": "på"},
                {"prompt": "Bananskalet ___ (فعل)", "answer": "ligger"},
                {"prompt": "Bananskalet ligger ___ (حرف اضافه) golvet.", "answer": "på"},
                {"prompt": "Kartan ___ (فعل)", "answer": "ligger"},
                {"prompt": "Kartan ligger ___ (حرف اضافه) datorn.", "answer": "under", "accept": ["vid"]},
                {"prompt": "Sängbordet ___ (فعل)", "answer": "står"},
                {"prompt": "Sängbordet står ___ (حرف اضافه) sängen.", "answer": "bredvid", "accept": ["till vänster om"]},
                {"prompt": "Påsen ___ (فعل)", "answer": "ligger"},
                {"prompt": "Påsen ligger ___ (حرف اضافه) sängen.", "answer": "på"},
            ],
        },
        {
            "num": 6, "title": "Adjektiv och substantiv", "type": "fill",
            "instructions": "شکل درست صفت و اسم رو بنویس.",
            "items": [
                {"prompt": "Har du sett Fabians ___ (صفت: ny)", "answer": "nya"},
                {"prompt": "Har du sett Fabians nya ___ (اسم: lägenhet)?", "answer": "lägenhet"},
                {"prompt": "Igår köpte jag de här ___ (صفت: gul)", "answer": "gula"},
                {"prompt": "Igår köpte jag de här gula ___ (اسم: sko، جمع معرفه)." , "answer": "skorna"},
                {"prompt": "Lukas har två ___ (صفت: söt)", "answer": "söta"},
                {"prompt": "Lukas har två söta ___ (اسم: katt، جمع).", "answer": "katter"},
                {"prompt": "Har någon sett min ___ (صفت: svart)", "answer": "svarta"},
                {"prompt": "Har någon sett min svarta ___ (اسم: tröja)?", "answer": "tröja"},
                {"prompt": "Anneli har ett ___ (صفت: stor)", "answer": "stort"},
                {"prompt": "Anneli har ett stort ___ (اسم: hus).", "answer": "hus"},
                {"prompt": "Den ___ (صفت: liten، معرفه)", "answer": "lilla"},
                {"prompt": "Den lilla ___ (اسم: pojke، معرفه) tycker om att cykla i parken.", "answer": "pojken"},
                {"prompt": "Margit har två ___ (صفت: liten، جمع)", "answer": "små"},
                {"prompt": "Margit har två små ___ (اسم: hund، جمع).", "answer": "hundar"},
            ],
        },
        {
            "num": 7, "title": "Ord", "type": "mcq",
            "instructions": "گزینه‌ی درست رو انتخاب کن.",
            "items": [
                {"prompt": "Man brukar elda i en …", "options": ["korridor.", "tvättstuga.", "öppen spis."], "correct": 2},
                {"prompt": "En särbo …",
                 "options": ["bor hos sina föräldrar.", "bor ihop med sin partner.", "bor inte ihop med sin partner."], "correct": 2},
                {"prompt": "Om man bor långt från jobbet måste man …", "options": ["dela.", "hämta.", "pendla."], "correct": 2},
                {"prompt": "På sin tomt brukar man …", "options": ["ha blommor.", "laga mat.", "renovera."], "correct": 0},
                {"prompt": "Om en lägenhet är i bra skick …",
                 "options": ["måste man måla och reparera den.", "har man förråd i källaren eller på vinden.",
                             "behöver man inte renovera den."], "correct": 2},
                {"prompt": "Om man bor i en förort bor man …", "options": ["i stan.", "på landet.", "strax utanför stan."], "correct": 2},
                {"prompt": "Om man bor i en bostadsrätt …",
                 "options": ["hyr man sin lägenhet.", "har man köpt sin lägenhet.", "delar man sin lägenhet med någon annan."], "correct": 1},
            ],
        },
        {
            "num": 8, "title": "Se + adjektiv + ut", "type": "fill",
            "instructions": "با se ut جمله بساز (مثال: Hon såg trevlig ut.).",
            "items": [
                {"prompt": "Det finns många kaféer i Gamla Stan. → ___ . (de, mysig)", "answer": "De ser mysiga ut."},
                {"prompt": "Märta och Dick har köpt ett nytt hus. → ___ . (det, fin)", "answer": "Det ser fint ut.",
                 "accept": ["Det såg fint ut."]},
                {"prompt": "Förra veckan kom familjen Ek hem till oss. → ___ . (deras, döttrar, glad)",
                 "answer": "Deras döttrar såg glada ut."},
                {"prompt": "Vivi har ett stort piano. → ___ . (det, dyr)", "answer": "Det ser dyrt ut."},
                {"prompt": "Morfar ville köpa en ny dator, men han tyckte att ___ . (den, liten)", "answer": "den såg liten ut."},
            ],
        },
        {
            "num": 9, "title": "Kroppen", "type": "fill",
            "instructions": "اسم این قسمت‌های بدن رو بنویس.",
            "items": [
                {"prompt": "۱ (گونه)", "answer": "en kind"},
                {"prompt": "۲ (چانه)", "answer": "en haka"},
                {"prompt": "۳ (گردن)", "answer": "en hals"},
                {"prompt": "۴ (سینه)", "answer": "ett bröst"},
                {"prompt": "۵ (کمر/میان‌تنه)", "answer": "en midja"},
                {"prompt": "۶ (بازو)", "answer": "en arm"},
                {"prompt": "۷ (شکم)", "answer": "en mage"},
                {"prompt": "۸ (پا - ساق)", "answer": "ett ben"},
                {"prompt": "۹ (ران)", "answer": "ett lår"},
                {"prompt": "۱۰ (کف پا)", "answer": "en fot"},
            ],
        },
        {
            "num": 10, "title": "Tidsprepositioner", "type": "fill",
            "instructions": "حرف اضافه‌ی زمان مناسب رو بنویس.",
            "items": [
                {"prompt": "Elisa dricker fem koppar kaffe ___ dagen.", "answer": "om"},
                {"prompt": "Tåget går fyra gånger ___ timmen.", "answer": "i"},
                {"prompt": "Stefan spelar tennis två gånger ___ veckan.", "answer": "i"},
                {"prompt": "Jenny tar upp sin mobil två gånger ___ minuten.", "answer": "i"},
                {"prompt": "En gång ___ året åker Pedro till Brasilien.", "answer": "om"},
            ],
        },
        {
            "num": 11, "title": "Adverb", "type": "fill",
            "instructions": "صفت رو از این‌ها انتخاب و به قید تبدیل کن: långsam, dålig, försiktig, djup, hård.",
            "items": [
                {"prompt": "Albin hörde inte telefonen eftersom han sov så ___ .", "answer": "djupt"},
                {"prompt": "Vera tränar ___ . Hon springer eller går på gym nästan varje dag.", "answer": "hårt"},
                {"prompt": "Henry mådde ___ och gick hem efter lunch.", "answer": "dåligt"},
                {"prompt": "Du går så ___ . Vi missar bussen om du inte kan gå lite snabbare.", "answer": "långsamt"},
                {"prompt": "Man måste köra ___ där det finns många barn.", "answer": "försiktigt"},
            ],
        },
        {
            "num": 12, "title": "Varje, varannan…", "type": "fill",
            "instructions": "با کمک عدد داخل پرانتز، عبارت زمانی درست رو بنویس (مثال: 3 → var tredje).",
            "items": [
                {"prompt": "Paul tar en långsemester ___ (2) år.", "answer": "vartannat"},
                {"prompt": "Olga hälsar på sin faster i Luleå ___ (5) vecka.", "answer": "var femte"},
                {"prompt": "De tvättar fönstren ___ (4) månad ungefär.", "answer": "var fjärde"},
                {"prompt": "Tina jobbar extra ___ (6) helg.", "answer": "var sjätte"},
                {"prompt": "Våra grannar målar om sitt hus ___ (7) år.", "answer": "vart sjunde"},
            ],
        },
    ],
}

FRAMSTEGSTESTER = {
    1: FRAMSTEGSTEST_1,
    2: FRAMSTEGSTEST_2,
    3: FRAMSTEGSTEST_3,
    4: FRAMSTEGSTEST_4,
    5: FRAMSTEGSTEST_5,
    6: FRAMSTEGSTEST_6,
}
